package com.company.speedment.orm.test.project_1.db0.hares.hare.impl;

import com.company.speedment.orm.test.project_1.db0.hares.hare.Hare;
import com.company.speedment.orm.test.project_1.db0.hares.hare.HareBuilder;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'project_1.db0.hares.hare'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class HareImpl implements HareBuilder {
    
    private Integer id;
    private String name;
    private String color;
    private Integer age;
    
    public HareImpl() {
        
    }
    
    public HareImpl(final Hare hare) {
        setId(hare.getId());
        setName(hare.getName());
        setColor(hare.getColor());
        setAge(hare.getAge());
    }
    
    @Override
    public Integer getId() {
        return id;
    }
    
    @Override
    public HareImpl setId(Integer id) {
        this.id = id;
        return this;
    }
    
    @Override
    public String getName() {
        return name;
    }
    
    @Override
    public HareImpl setName(String name) {
        this.name = name;
        return this;
    }
    
    @Override
    public String getColor() {
        return color;
    }
    
    @Override
    public HareImpl setColor(String color) {
        this.color = color;
        return this;
    }
    
    @Override
    public Integer getAge() {
        return age;
    }
    
    @Override
    public HareImpl setAge(Integer age) {
        this.age = age;
        return this;
    }
    
    @Override
    public Hare build() {
        return new HareImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("name = "+Objects.toString(getName()));
        sj.add("color = "+Objects.toString(getColor()));
        sj.add("age = "+Objects.toString(getAge()));
        return "HareImpl "+sj.toString();
    }
}