package com.company.speedment.orm.test.project_1.db0.hares.human;

import com.speedment.core.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'project_1.db0.hares.human'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface HumanBuilder extends Human, Buildable<Human> {
    
    HumanBuilder setId(Integer id);
    
    HumanBuilder setName(String name);
}