package com.company.speedment.orm.test.hare;

import com.speedment.orm.runtime.SpeedmentApplicationLifecycle;

/**
 * A Speedment Application Lifecycle representing an entity (for example, a row) in the Project 'hare'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
public class HareApplication extends SpeedmentApplicationLifecycle<HareApplication> {
    
    public HareApplication() {
        setSpeedmentApplicationMetadata(new HareApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        loadAndSetProject();
        put(new com.company.speedment.orm.test.hare.db0.hares.carrot.impl.CarrotManagerImpl());
        put(new com.company.speedment.orm.test.hare.db0.hares.hare.impl.HareManagerImpl());
        put(new com.company.speedment.orm.test.hare.db0.hares.human.impl.HumanManagerImpl());
        super.onInit();
    }
}