package com.company.speedment.orm.test.hare.db0.hares.human.impl;

import com.company.speedment.orm.test.hare.db0.hares.human.Human;
import com.company.speedment.orm.test.hare.db0.hares.human.HumanBuilder;
import com.company.speedment.orm.test.hare.db0.hares.human.HumanManager;
import com.speedment.core.core.manager.sql.AbstractSqlManager;
import com.speedment.core.exception.SpeedmentException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * A manager implementation representing an entity (for example, a row) in the Table 'hare.db0.hares.human'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class HumanManagerImpl extends AbstractSqlManager<Integer, Human, HumanBuilder> implements HumanManager {
    
    public HumanManagerImpl() {
        setSqlEntityMapper(this::defaultReadEntity);
    }
    
    @Override
    public HumanBuilder builder() {
        return new HumanImpl();
    }
    
    @Override
    public HumanBuilder toBuilder(Human prototype) {
        return new HumanImpl(prototype);
    }
    
    protected Human defaultReadEntity(ResultSet resultSet) {
        final HumanBuilder builder = builder();
        try {
            builder.setId(resultSet.getInt("id"));
            builder.setName(getString(resultSet, "name"));
        }
        catch (SQLException sqle) {
            throw new SpeedmentException(sqle);
        }
        return builder;
    }
}