package com.company.speedment.orm.test.hare.db0.hares.carrot.impl;

import com.company.speedment.orm.test.hare.db0.hares.carrot.Carrot;
import com.company.speedment.orm.test.hare.db0.hares.carrot.CarrotBuilder;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'hare.db0.hares.carrot'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class CarrotImpl implements CarrotBuilder {
    
    private Integer id;
    private String name;
    private Integer hare;
    
    public CarrotImpl() {
        
    }
    
    public CarrotImpl(final Carrot carrot) {
        setId(carrot.getId());
        setName(carrot.getName());
        setHare(carrot.getHare());
    }
    
    @Override
    public Integer getId() {
        return id;
    }
    
    @Override
    public CarrotImpl setId(Integer id) {
        this.id = id;
        return this;
    }
    
    @Override
    public String getName() {
        return name;
    }
    
    @Override
    public CarrotImpl setName(String name) {
        this.name = name;
        return this;
    }
    
    @Override
    public Integer getHare() {
        return hare;
    }
    
    @Override
    public CarrotImpl setHare(Integer hare) {
        this.hare = hare;
        return this;
    }
    
    @Override
    public Carrot build() {
        return new CarrotImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("name = "+Objects.toString(getName()));
        sj.add("hare = "+Objects.toString(getHare()));
        return "CarrotImpl "+sj.toString();
    }
}