package com.company.speedment.orm.test.hello.db0.hellospeedment;

import com.speedment.orm.config.model.Column;
import com.speedment.orm.config.model.Table;
import com.speedment.orm.core.manager.Manager;
import com.speedment.orm.platform.Platform;
import com.speedment.orm.platform.component.ManagerComponent;
import com.speedment.orm.platform.component.ProjectComponent;
import java.lang.IllegalArgumentException;
import javax.annotation.Generated;

/**
 * A manager representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.image'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface ImageManager extends Manager<Integer, Image, ImageBuilder> {
    
    @Override
    default Integer primaryKeyFor(Image entity) {
        return entity.getId();
    }
    
    @Override
    default Table getTable() {
        return Platform.get().get(ProjectComponent.class).getProject().findTableByName("hello.db0.hellospeedment");
    }
    
    @Override
    default Class<ImageManager> getManagerClass() {
        return ImageManager.class;
    }
    
    @Override
    default Class<Image> getEntityClass() {
        return Image.class;
    }
    
    @Override
    default Class<ImageBuilder> getBuilderClass() {
        return ImageBuilder.class;
    }
    
    @Override
    default Object get(Image entity, Column column) {
        switch (column.getName()) {
            case "src" : return entity.getSrc();
            case "published" : return entity.getPublished();
            case "author" : return entity.getAuthor();
            case "description" : return entity.getDescription();
            case "title" : return entity.getTitle();
            case "id" : return entity.getId();
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @SuppressWarnings("unchecked")
    static ImageManager get() {
        return (ImageManager) Platform.get().get(ManagerComponent.class).manager(ImageManager.class);
    }
}