package com.company.speedment.orm.test.hello.db0.hellospeedment;

import com.speedment.orm.core.Buildable;
import java.time.LocalDateTime;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.image'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface ImageBuilder extends Image, Buildable<Image> {
    
    ImageBuilder setSrc(String src);
    
    ImageBuilder setPublished(LocalDateTime published);
    
    ImageBuilder setAuthor(Integer author);
    
    ImageBuilder setDescription(String description);
    
    ImageBuilder setTitle(String title);
    
    ImageBuilder setId(Integer id);
}