package com.company.speedment.orm.test.hello.db0.hellospeedment;

import com.speedment.orm.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.user'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface UserBuilder extends User, Buildable<User> {
    
    UserBuilder setMail(String mail);
    
    UserBuilder setId(Integer id);
}