package com.company.speedment.orm.test.hello.db0.hellospeedment;

import com.speedment.orm.config.model.Column;
import com.speedment.orm.config.model.Table;
import com.speedment.orm.core.manager.Manager;
import com.speedment.orm.platform.Platform;
import com.speedment.orm.platform.component.ManagerComponent;
import com.speedment.orm.platform.component.ProjectComponent;
import java.lang.IllegalArgumentException;
import javax.annotation.Generated;

/**
 * A manager representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.visit'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface VisitManager extends Manager<Integer, Visit, VisitBuilder> {
    
    @Override
    default Integer primaryKeyFor(Visit entity) {
        return entity.getId();
    }
    
    @Override
    default Table getTable() {
        return Platform.get().get(ProjectComponent.class).getProject().findTableByName("hello.db0.hellospeedment");
    }
    
    @Override
    default Class<VisitManager> getManagerClass() {
        return VisitManager.class;
    }
    
    @Override
    default Class<Visit> getEntityClass() {
        return Visit.class;
    }
    
    @Override
    default Class<VisitBuilder> getBuilderClass() {
        return VisitBuilder.class;
    }
    
    @Override
    default Object get(Visit entity, Column column) {
        switch (column.getName()) {
            case "image" : return entity.getImage();
            case "user" : return entity.getUser();
            case "time" : return entity.getTime();
            case "id" : return entity.getId();
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @SuppressWarnings("unchecked")
    static VisitManager get() {
        return (VisitManager) Platform.get().get(ManagerComponent.class).manager(VisitManager.class);
    }
}