package com.company.speedment.orm.test.hello.db0.hellospeedment;

import com.speedment.orm.core.Buildable;
import java.time.LocalDateTime;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.visit'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface VisitBuilder extends Visit, Buildable<Visit> {
    
    VisitBuilder setImage(String image);
    
    VisitBuilder setUser(Integer user);
    
    VisitBuilder setTime(LocalDateTime time);
    
    VisitBuilder setId(Integer id);
}