package com.company.speedment.orm.test.hello.db0.hellospeedment;

import java.time.LocalDateTime;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.visit'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface Visit {
    
    String getImage();
    
    Integer getUser();
    
    LocalDateTime getTime();
    
    Integer getId();
}