package com.company.speedment.orm.test.hello.db0.hellospeedment.impl;

import com.company.speedment.orm.test.hello.db0.hellospeedment.Image;
import com.company.speedment.orm.test.hello.db0.hellospeedment.ImageBuilder;
import com.company.speedment.orm.test.hello.db0.hellospeedment.ImageManager;
import com.speedment.orm.core.manager.AbstractManager;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * A manager implementation representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.image'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class ImageManagerImpl extends AbstractManager<Integer, Image, ImageBuilder> implements ImageManager {
    
    @Override
    public ImageBuilder builder() {
        return new ImageImpl();
    }
    
    @Override
    public ImageBuilder toBuilder(Image prototype) {
        return new ImageImpl(prototype);
    }
    
    @Override
    public Stream<Image> stream() {
        return Stream.empty();
    }
    
    @Override
    public Image persist(Image entity) {
        return entity;
    }
    
    @Override
    public Image remove(Image entity) {
        return entity;
    }
}