package com.company.speedment.orm.test.hello.db0.hellospeedment.impl;

import com.company.speedment.orm.test.hello.db0.hellospeedment.Transition;
import com.company.speedment.orm.test.hello.db0.hellospeedment.TransitionBuilder;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.transition'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class TransitionImpl implements TransitionBuilder {
    
    private Integer to;
    private Integer from;
    
    public TransitionImpl() {
        
    }
    
    public TransitionImpl(final Transition transition) {
        setTo(transition.getTo());
        setFrom(transition.getFrom());
    }
    
    @Override
    public Integer getTo() {
        return to;
    }
    
    @Override
    public TransitionImpl setTo(Integer to) {
        this.to = to;
        return this;
    }
    
    @Override
    public Integer getFrom() {
        return from;
    }
    
    @Override
    public TransitionImpl setFrom(Integer from) {
        this.from = from;
        return this;
    }
    
    @Override
    public Transition build() {
        return new TransitionImpl(this);
    }
}