package com.company.speedment.orm.test.hello.db0.hellospeedment.impl;

import com.company.speedment.orm.test.hello.db0.hellospeedment.User;
import com.company.speedment.orm.test.hello.db0.hellospeedment.UserBuilder;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.user'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class UserImpl implements UserBuilder {
    
    private String mail;
    private Integer id;
    
    public UserImpl() {
        
    }
    
    public UserImpl(final User user) {
        setMail(user.getMail());
        setId(user.getId());
    }
    
    @Override
    public String getMail() {
        return mail;
    }
    
    @Override
    public UserImpl setMail(String mail) {
        this.mail = mail;
        return this;
    }
    
    @Override
    public Integer getId() {
        return id;
    }
    
    @Override
    public UserImpl setId(Integer id) {
        this.id = id;
        return this;
    }
    
    @Override
    public User build() {
        return new UserImpl(this);
    }
}