package com.company.speedment.orm.test.hello.db0.hellospeedment.impl;

import com.company.speedment.orm.test.hello.db0.hellospeedment.User;
import com.company.speedment.orm.test.hello.db0.hellospeedment.UserBuilder;
import com.company.speedment.orm.test.hello.db0.hellospeedment.UserManager;
import com.speedment.orm.core.manager.AbstractManager;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * A manager implementation representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.user'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class UserManagerImpl extends AbstractManager<Integer, User, UserBuilder> implements UserManager {
    
    @Override
    public UserBuilder builder() {
        return new UserImpl();
    }
    
    @Override
    public UserBuilder toBuilder(User prototype) {
        return new UserImpl(prototype);
    }
    
    @Override
    public Stream<User> stream() {
        return Stream.empty();
    }
    
    @Override
    public User persist(User entity) {
        return entity;
    }
    
    @Override
    public User remove(User entity) {
        return entity;
    }
}