package com.company.speedment.orm.test.hello.db0.hellospeedment.impl;

import com.company.speedment.orm.test.hello.db0.hellospeedment.Visit;
import com.company.speedment.orm.test.hello.db0.hellospeedment.VisitBuilder;
import java.time.LocalDateTime;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.visit'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class VisitImpl implements VisitBuilder {
    
    private String image;
    private Integer user;
    private LocalDateTime time;
    private Integer id;
    
    public VisitImpl() {
        
    }
    
    public VisitImpl(final Visit visit) {
        setImage(visit.getImage());
        setUser(visit.getUser());
        setTime(visit.getTime());
        setId(visit.getId());
    }
    
    @Override
    public String getImage() {
        return image;
    }
    
    @Override
    public VisitImpl setImage(String image) {
        this.image = image;
        return this;
    }
    
    @Override
    public Integer getUser() {
        return user;
    }
    
    @Override
    public VisitImpl setUser(Integer user) {
        this.user = user;
        return this;
    }
    
    @Override
    public LocalDateTime getTime() {
        return time;
    }
    
    @Override
    public VisitImpl setTime(LocalDateTime time) {
        this.time = time;
        return this;
    }
    
    @Override
    public Integer getId() {
        return id;
    }
    
    @Override
    public VisitImpl setId(Integer id) {
        this.id = id;
        return this;
    }
    
    @Override
    public Visit build() {
        return new VisitImpl(this);
    }
}