package com.company.speedment.orm.test.hello.db0.hellospeedment.impl;

import com.company.speedment.orm.test.hello.db0.hellospeedment.Visit;
import com.company.speedment.orm.test.hello.db0.hellospeedment.VisitBuilder;
import com.company.speedment.orm.test.hello.db0.hellospeedment.VisitManager;
import com.speedment.orm.core.manager.AbstractManager;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * A manager implementation representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.visit'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class VisitManagerImpl extends AbstractManager<Integer, Visit, VisitBuilder> implements VisitManager {
    
    @Override
    public VisitBuilder builder() {
        return new VisitImpl();
    }
    
    @Override
    public VisitBuilder toBuilder(Visit prototype) {
        return new VisitImpl(prototype);
    }
    
    @Override
    public Stream<Visit> stream() {
        return Stream.empty();
    }
    
    @Override
    public Visit persist(Visit entity) {
        return entity;
    }
    
    @Override
    public Visit remove(Visit entity) {
        return entity;
    }
}