package com.company.speedment.orm.test.project_1.db0.hares.human.impl;

import com.company.speedment.orm.test.project_1.db0.hares.human.Human;
import com.company.speedment.orm.test.project_1.db0.hares.human.HumanBuilder;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'project_1.db0.hares.human'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class HumanImpl implements HumanBuilder {
    
    private Integer id;
    private String name;
    
    public HumanImpl() {
        
    }
    
    public HumanImpl(final Human human) {
        setId(human.getId());
        setName(human.getName());
    }
    
    @Override
    public Integer getId() {
        return id;
    }
    
    @Override
    public HumanImpl setId(Integer id) {
        this.id = id;
        return this;
    }
    
    @Override
    public String getName() {
        return name;
    }
    
    @Override
    public HumanImpl setName(String name) {
        this.name = name;
        return this;
    }
    
    @Override
    public Human build() {
        return new HumanImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("name = "+Objects.toString(getName()));
        return "HumanImpl "+sj.toString();
    }
}