package com.company.speedment.orm.test.hello;

import com.speedment.orm.runtime.SpeedmentApplicationLifecycle;

/**
 * A Speedment Application Lifecycle representing an entity (for example, a row) in the Project 'hello'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
public class HelloApplication extends SpeedmentApplicationLifecycle<HelloApplication> {
    
    public HelloApplication() {
        setConfigDirectoryName("src/main/groovy");
        setConfigFileName("speedment.groovy");
    }
    
    @Override
    public void onInit() {
        loadAndSetProject();
        put(new com.company.speedment.orm.test.hello.db0.hellospeedment.impl.ImageManagerImpl());
        put(new com.company.speedment.orm.test.hello.db0.hellospeedment.impl.TransitionManagerImpl());
        put(new com.company.speedment.orm.test.hello.db0.hellospeedment.impl.UserManagerImpl());
        put(new com.company.speedment.orm.test.hello.db0.hellospeedment.impl.VisitManagerImpl());
        super.onInit();
    }
}