package com.company.speedment.orm.test.hello;

import com.speedment.core.runtime.SpeedmentApplicationLifecycle;

/**
 * A Speedment Application Lifecycle representing an entity (for example, a row) in the Project 'hello'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
public class HelloApplication extends SpeedmentApplicationLifecycle<HelloApplication> {
    
    public HelloApplication() {
        setSpeedmentApplicationMetadata(new HelloApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        loadAndSetProject();
        put(new com.company.speedment.orm.test.hello.db0.hellospeedment.image.impl.ImageManagerImpl());
        put(new com.company.speedment.orm.test.hello.db0.hellospeedment.transition.impl.TransitionManagerImpl());
        put(new com.company.speedment.orm.test.hello.db0.hellospeedment.user.impl.UserManagerImpl());
        put(new com.company.speedment.orm.test.hello.db0.hellospeedment.visit.impl.VisitManagerImpl());
        super.onInit();
    }
}