package com.company.speedment.orm.test.hare.db0.hares.carrot;

import com.speedment.orm.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'hare.db0.hares.carrot'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface CarrotBuilder extends Carrot, Buildable<Carrot> {
    
    CarrotBuilder setId(Integer id);
    
    CarrotBuilder setName(String name);
    
    CarrotBuilder setHare(Integer hare);
}