package com.company.speedment.orm.test.hello.db0.hellospeedment.transition.impl;

import com.company.speedment.orm.test.hello.db0.hellospeedment.transition.Transition;
import com.company.speedment.orm.test.hello.db0.hellospeedment.transition.TransitionBuilder;
import com.company.speedment.orm.test.hello.db0.hellospeedment.transition.TransitionManager;
import com.speedment.orm.core.manager.sql.AbstractSqlManager;
import java.lang.RuntimeException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * A manager implementation representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.transition'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class TransitionManagerImpl extends AbstractSqlManager<java.util.List<Integer>, Transition, TransitionBuilder> implements TransitionManager {
    
    public TransitionManagerImpl() {
        setSqlEntityMapper(this::defaultReadEntity);
    }
    
    @Override
    public TransitionBuilder builder() {
        return new TransitionImpl();
    }
    
    @Override
    public TransitionBuilder toBuilder(Transition prototype) {
        return new TransitionImpl(prototype);
    }
    
    protected Transition defaultReadEntity(ResultSet resultSet) {
        final TransitionBuilder builder = builder();
        try {
            builder.setFrom(resultSet.getInt("from"));
            builder.setTo(resultSet.getInt("to"));
        }
        catch (SQLException sqle) {
            throw new RuntimeException(sqle);
        }
        return builder;
    }
}