package com.company.speedment.orm.test.hello.db0.hellospeedment.transition.impl;

import com.company.speedment.orm.test.hello.db0.hellospeedment.transition.Transition;
import com.company.speedment.orm.test.hello.db0.hellospeedment.transition.TransitionBuilder;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.transition'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class TransitionImpl implements TransitionBuilder {
    
    private Integer from;
    private Integer to;
    
    public TransitionImpl() {
        
    }
    
    public TransitionImpl(final Transition transition) {
        setFrom(transition.getFrom());
        setTo(transition.getTo());
    }
    
    @Override
    public Integer getFrom() {
        return from;
    }
    
    @Override
    public final TransitionImpl setFrom(Integer from) {
        this.from = from;
        return this;
    }
    
    @Override
    public Integer getTo() {
        return to;
    }
    
    @Override
    public final TransitionImpl setTo(Integer to) {
        this.to = to;
        return this;
    }
    
    @Override
    public Transition build() {
        return new TransitionImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("from = "+Objects.toString(getFrom()));
        sj.add("to = "+Objects.toString(getTo()));
        return "TransitionImpl "+sj.toString();
    }
}