package com.company.speedment.orm.test.hello.db0.hellospeedment.visit;

import com.speedment.core.core.entity.Entity;
import com.speedment.core.core.manager.metaresult.MetaResult;
import java.lang.Integer;
import java.sql.Timestamp;
import java.util.Optional;
import java.util.function.Consumer;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.visit'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
@Entity(managerType = VisitManager.class,
        builderType = VisitBuilder.class,
        primaryKeyType = Integer.class)
public interface Visit {
    
    Integer getId();
    
    Timestamp getTime();
    
    Integer getUser();
    
    String getImage();
    
    static VisitBuilder builder() {
        return VisitManager.get().builder();
    }
    
    default VisitBuilder toBuilder() {
        return VisitManager.get().toBuilder(this);
    }
    
    default String toJson() {
        return VisitManager.get().toJson(this);
    }
    
    static Stream<Visit> stream() {
        return VisitManager.get().stream();
    }
    
    default Optional<Visit> persist() {
        return VisitManager.get().persist(this);
    }
    
    default Optional<Visit> update() {
        return VisitManager.get().update(this);
    }
    
    default Optional<Visit> remove() {
        return VisitManager.get().remove(this);
    }
    
    default Optional<Visit> persist(Consumer<MetaResult<Visit>> listener) {
        return VisitManager.get().persist(this, listener);
    }
    
    default Optional<Visit> update(Consumer<MetaResult<Visit>> listener) {
        return VisitManager.get().update(this, listener);
    }
    
    default Optional<Visit> remove(Consumer<MetaResult<Visit>> listener) {
        return VisitManager.get().remove(this, listener);
    }
}