/**
 *
 * Copyright (c) 2006-2015, Speedment, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); You may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.company.speedment.orm.test;

import com.speedment.orm.core.Buildable;
import java.time.LocalDateTime;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'Hello Speedment Project.db0.hellospeedment'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface ImageBuilder extends Image, Buildable<Image> {
    
    ImageBuilder setSrc(String src);
    
    ImageBuilder setPublished(LocalDateTime published);
    
    ImageBuilder setAuthor(Integer author);
    
    ImageBuilder setDescription(String description);
    
    ImageBuilder setTitle(String title);
    
    ImageBuilder setId(Integer id);
}