package com.company.speedment.orm.test.hello.db0.hellospeedment.image;

import java.sql.Timestamp;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.image'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface Image {
    
    Integer getId();
    
    String getTitle();
    
    String getDescription();
    
    Integer getAuthor();
    
    Timestamp getPublished();
    
    String getSrc();
}