package com.company.speedment.orm.test.hello.db0.hellospeedment.transition;

import com.speedment.core.field.reference.ComparableReferenceField;
import javax.annotation.Generated;
import static com.speedment.core.field.FieldUtil.findColumn;

/**
 * Interface representing the fields of an entity.
 * 
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public final class TransitionField {
    
    public final static ComparableReferenceField<Transition, Integer> FROM = new ComparableReferenceField<>(() -> findColumn(Transition.class, "from"), Transition::getFrom);
    public final static ComparableReferenceField<Transition, Integer> TO = new ComparableReferenceField<>(() -> findColumn(Transition.class, "to"), Transition::getTo);
    
    private TransitionField() {
        
    }
}