package com.company.speedment.orm.test.hello.db0.hellospeedment.transition;

import java.util.Optional;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.transition'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface Transition {
    
    Integer getFrom();
    
    Integer getTo();
    
    static TransitionBuilder builder() {
        return TransitionManager.get().builder();
    }
    
    default TransitionBuilder toBuilder() {
        return TransitionManager.get().toBuilder(this);
    }
    
    default String toJson() {
        return TransitionManager.get().toJson(this);
    }
    
    static Stream<Transition> stream() {
        return TransitionManager.get().stream();
    }
    
    default Optional<Transition> persist() {
        return TransitionManager.get().persist(this);
    }
    
    default Optional<Transition> update() {
        return TransitionManager.get().update(this);
    }
    
    default Optional<Transition> remove() {
        return TransitionManager.get().remove(this);
    }
}