package com.company.speedment.orm.test.hare.db0.hares.hare;

import com.speedment.core.field.reference.ComparableReferenceField;
import com.speedment.core.field.reference.string.StringReferenceField;
import javax.annotation.Generated;
import static com.speedment.core.field.FieldUtil.findColumn;

/**
 * Interface representing the fields of an entity.
 * 
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public final class HareField {
    
    public final static ComparableReferenceField<Hare, Integer> ID = new ComparableReferenceField<>(() -> findColumn(Hare.class, "id"), Hare::getId);
    public final static StringReferenceField<Hare> NAME = new StringReferenceField<>(() -> findColumn(Hare.class, "name"), o -> o.getName().orElse(null));
    public final static StringReferenceField<Hare> COLOR = new StringReferenceField<>(() -> findColumn(Hare.class, "color"), o -> o.getColor().orElse(null));
    public final static ComparableReferenceField<Hare, Integer> AGE = new ComparableReferenceField<>(() -> findColumn(Hare.class, "age"), o -> o.getAge().orElse(null));
    
    private HareField() {
        
    }
}