package com.company.speedment.orm.test.project_1;

import com.speedment.core.runtime.SpeedmentApplicationLifecycle;

/**
 * A Speedment Application Lifecycle representing an entity (for example, a row) in the Project 'project_1'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
public class Project1Application extends SpeedmentApplicationLifecycle<Project1Application> {
    
    public Project1Application() {
        setSpeedmentApplicationMetadata(new Project1ApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        loadAndSetProject();
        put(new com.company.speedment.orm.test.project_1.db0.hares.carrot.impl.CarrotManagerImpl());
        put(new com.company.speedment.orm.test.project_1.db0.hares.hare.impl.HareManagerImpl());
        put(new com.company.speedment.orm.test.project_1.db0.hares.human.impl.HumanManagerImpl());
        super.onInit();
    }
}