package com.company.speedment.orm.test.project_1.db0.hares.hare;

import com.speedment.core.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'project_1.db0.hares.hare'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface HareBuilder extends Hare, Buildable<Hare> {
    
    HareBuilder setId(Integer id);
    
    HareBuilder setName(String name);
    
    HareBuilder setColor(String color);
    
    HareBuilder setAge(Integer age);
}