package com.company.speedment.orm.test.hello.db0.hellospeedment.user;

import com.speedment.core.core.entity.Entity;
import com.speedment.core.core.manager.metaresult.MetaResult;
import java.lang.Integer;
import java.util.Optional;
import java.util.function.Consumer;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.user'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
@Entity(managerType = UserManager.class,
        builderType = UserBuilder.class,
        primaryKeyType = Integer.class)
public interface User {
    
    Integer getId();
    
    String getMail();
    
    static UserBuilder builder() {
        return UserManager.get().builder();
    }
    
    default UserBuilder toBuilder() {
        return UserManager.get().toBuilder(this);
    }
    
    default String toJson() {
        return UserManager.get().toJson(this);
    }
    
    static Stream<User> stream() {
        return UserManager.get().stream();
    }
    
    default Optional<User> persist() {
        return UserManager.get().persist(this);
    }
    
    default Optional<User> update() {
        return UserManager.get().update(this);
    }
    
    default Optional<User> remove() {
        return UserManager.get().remove(this);
    }
    
    default Optional<User> persist(Consumer<MetaResult<User>> listener) {
        return UserManager.get().persist(this, listener);
    }
    
    default Optional<User> update(Consumer<MetaResult<User>> listener) {
        return UserManager.get().update(this, listener);
    }
    
    default Optional<User> remove(Consumer<MetaResult<User>> listener) {
        return UserManager.get().remove(this, listener);
    }
}