package com.company.speedment.orm.test.hello.db0.hellospeedment.user;

import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.user'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface User {
    
    Integer getId();
    
    String getMail();
}