package com.company.speedment.orm.test.hello.db0.hellospeedment.image.impl;

import com.company.speedment.orm.test.hello.db0.hellospeedment.image.Image;
import com.company.speedment.orm.test.hello.db0.hellospeedment.image.ImageBuilder;
import java.sql.Time;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'hello.db0.hellospeedment.image'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class ImageImpl implements ImageBuilder {
    
    private Integer id;
    private String title;
    private String description;
    private Integer author;
    private Time published;
    private String src;
    
    public ImageImpl() {
        
    }
    
    public ImageImpl(final Image image) {
        setId(image.getId());
        setTitle(image.getTitle());
        setDescription(image.getDescription());
        setAuthor(image.getAuthor());
        setPublished(image.getPublished());
        setSrc(image.getSrc());
    }
    
    @Override
    public Integer getId() {
        return id;
    }
    
    @Override
    public ImageImpl setId(Integer id) {
        this.id = id;
        return this;
    }
    
    @Override
    public String getTitle() {
        return title;
    }
    
    @Override
    public ImageImpl setTitle(String title) {
        this.title = title;
        return this;
    }
    
    @Override
    public String getDescription() {
        return description;
    }
    
    @Override
    public ImageImpl setDescription(String description) {
        this.description = description;
        return this;
    }
    
    @Override
    public Integer getAuthor() {
        return author;
    }
    
    @Override
    public ImageImpl setAuthor(Integer author) {
        this.author = author;
        return this;
    }
    
    @Override
    public Time getPublished() {
        return published;
    }
    
    @Override
    public ImageImpl setPublished(Time published) {
        this.published = published;
        return this;
    }
    
    @Override
    public String getSrc() {
        return src;
    }
    
    @Override
    public ImageImpl setSrc(String src) {
        this.src = src;
        return this;
    }
    
    @Override
    public Image build() {
        return new ImageImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("title = "+Objects.toString(getTitle()));
        sj.add("description = "+Objects.toString(getDescription()));
        sj.add("author = "+Objects.toString(getAuthor()));
        sj.add("published = "+Objects.toString(getPublished()));
        sj.add("src = "+Objects.toString(getSrc()));
        return "ImageImpl "+sj.toString();
    }
}