package com.company.speedment.orm.test.project_1.db0.hares.carrot;

import com.speedment.core.field.reference.ComparableReferenceField;
import com.speedment.core.field.reference.string.StringReferenceField;
import javax.annotation.Generated;
import static com.speedment.core.field.FieldUtil.findColumn;

/**
 * Interface representing the fields of an entity.
 * 
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public final class CarrotField {
    
    public final static ComparableReferenceField<Carrot, Integer> ID = new ComparableReferenceField<>(() -> findColumn(Carrot.class, "id"), Carrot::getId);
    public final static StringReferenceField<Carrot> NAME = new StringReferenceField<>(() -> findColumn(Carrot.class, "name"), Carrot::getName);
    public final static ComparableReferenceField<Carrot, Integer> OWNER = new ComparableReferenceField<>(() -> findColumn(Carrot.class, "owner"), Carrot::getOwner);
    public final static ComparableReferenceField<Carrot, Integer> RIVAL = new ComparableReferenceField<>(() -> findColumn(Carrot.class, "rival"), Carrot::getRival);
    
    private CarrotField() {
        
    }
}